In [116]:
# DEPENDENCIES
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as st
from datetime import datetime

# DATA FILES
path_crime_data = "Data/crime_data.csv"

# READ CRIME DATA
raw_crime_data = pd.read_csv(path_crime_data)
raw_crime_data

,Website Region,WAPOL_Hierarchy_order_Lvl1,WAPOL_Hierarchy_Lvl1,WAPOL_Hierarchy_order_Lvl2,WAPOL_Hierarchy_Lvl2,Period,Year,Key,MonthYear,COUNT_of_Offnc_ID
0,Armadale District,1.1,Murder,1,Homicide,1-Jan-07,2006-07,Armadale DistrictMurderHomicide12007,12007,NaN
1,Armadale District,1.1,Murder,1,Homicide,1-Feb-07,2006-07,Armadale DistrictMurderHomicide22007,22007,NaN
2,Armadale District,1.1,Murder,1,Homicide,1-Mar-07,2006-07,Armadale DistrictMurderHomicide32007,32007,1.0
3,Armadale District,1.1,Murder,1,Homicide,1-Apr-07,2006-07,Armadale DistrictMurderHomicide42007,42007,NaN
4,Armadale District,1.1,Murder,1,Homicide,1-May-07,2006-07,Armadale DistrictMurderHomicide52007,52007,NaN
...,...,...,...,...,...,...,...,...,...,...
143095,Wheatbelt District,20.3,Breach of Police Order,20,Breach of Violence Restraint Order,1-Nov-19,2019-20,Wheatbelt DistrictBreach of Police OrderBreach...,112019,5.0
143096,Wheatbelt District,20.3,Breach of Police Order,20,Breach of Violence Restraint Order,1-Dec-19,2019-20,Wheatbelt DistrictBreach of Police OrderBreach...,122019,7.0
143097,Wheatbelt District,20.3,Breach of Police Order,20,Breach of Violence Restraint Order,1-Jan-20,2019-20,Wheatbelt DistrictBreach of Police OrderBreach...,12020,5.0
143098,Wheatbelt District,20.3,Breach of Police Order,20,Breach of Violence Restraint Order,1-Feb-20,2019-20,Wheatbelt DistrictBreach of Police OrderBreach...,22020,1.0
143099,Wheatbelt District,20.3,Breach of Police Order,20,Breach of Violence Restraint Order,1-Mar-20,2019-20,Wheatbelt DistrictBreach of Police OrderBreach...,32020,4.0

In [117]:
# DROP IRRELEVANT COLUMNS
del raw_crime_data['WAPOL_Hierarchy_order_Lvl1']

In [118]:
del raw_crime_data['WAPOL_Hierarchy_order_Lvl2']

In [119]:
del raw_crime_data['Year']

In [120]:
del raw_crime_data['Key']

In [121]:
del raw_crime_data['MonthYear']

In [122]:
raw_crime_data

,Website Region,WAPOL_Hierarchy_Lvl1,WAPOL_Hierarchy_Lvl2,Period,COUNT_of_Offnc_ID
0,Armadale District,Murder,Homicide,1-Jan-07,NaN
1,Armadale District,Murder,Homicide,1-Feb-07,NaN
2,Armadale District,Murder,Homicide,1-Mar-07,1.0
3,Armadale District,Murder,Homicide,1-Apr-07,NaN
4,Armadale District,Murder,Homicide,1-May-07,NaN
...,...,...,...,...,...
143095,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Nov-19,5.0
143096,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Dec-19,7.0
143097,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Jan-20,5.0
143098,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Feb-20,1.0
143099,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Mar-20,4.0

In [123]:
raw_crime_data = raw_crime_data.rename(columns={"Website Region":"District", 
                               "WAPOL_Hierarchy_Lvl1":"Offence Group", 
                               "WAPOL_Hierarchy_Lvl2":"Offence", 
                               "Period":"Offence Date", 
                               "COUNT_of_Offnc_ID":"Total Number of Offences"})
raw_crime_data

,District,Offence Group,Offence,Offence Date,Total Number of Offences
0,Armadale District,Murder,Homicide,1-Jan-07,NaN
1,Armadale District,Murder,Homicide,1-Feb-07,NaN
2,Armadale District,Murder,Homicide,1-Mar-07,1.0
3,Armadale District,Murder,Homicide,1-Apr-07,NaN
4,Armadale District,Murder,Homicide,1-May-07,NaN
...,...,...,...,...,...
143095,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Nov-19,5.0
143096,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Dec-19,7.0
143097,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Jan-20,5.0
143098,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Feb-20,1.0
143099,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Mar-20,4.0

In [124]:
list(raw_crime_data.columns)

['District',
 'Offence Group',
 'Offence',
 'Offence Date',
 'Total Number of Offences']

In [125]:
# new data frame with split value columns 
new = raw_crime_data["Offence Date"].str.split("-", n = 2, expand = True) 
# making separate first name column from new data frame 
raw_crime_data["Month"]= new[1]
# making separate last name column from new data frame 
raw_crime_data["Year"]= new[2]
raw_crime_data

,District,Offence Group,Offence,Offence Date,Total Number of Offences,Month,Year
0,Armadale District,Murder,Homicide,1-Jan-07,NaN,Jan,07
1,Armadale District,Murder,Homicide,1-Feb-07,NaN,Feb,07
2,Armadale District,Murder,Homicide,1-Mar-07,1.0,Mar,07
3,Armadale District,Murder,Homicide,1-Apr-07,NaN,Apr,07
4,Armadale District,Murder,Homicide,1-May-07,NaN,May,07
...,...,...,...,...,...,...,...
143095,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Nov-19,5.0,Nov,19
143096,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Dec-19,7.0,Dec,19
143097,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Jan-20,5.0,Jan,20
143098,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Feb-20,1.0,Feb,20
143099,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1-Mar-20,4.0,Mar,20

In [126]:
del raw_crime_data['Offence Date']

In [127]:
#convert year column from string into integer
raw_crime_data['Year'] = raw_crime_data['Year'].astype(int)

In [128]:
#remove data prior to 2010
raw_crime_data=raw_crime_data.loc[raw_crime_data["Year"]>=10]
raw_crime_data

,District,Offence Group,Offence,Total Number of Offences,Month,Year
36,Armadale District,Murder,Homicide,2.0,Jan,10
37,Armadale District,Murder,Homicide,2.0,Feb,10
38,Armadale District,Murder,Homicide,NaN,Mar,10
39,Armadale District,Murder,Homicide,NaN,Apr,10
40,Armadale District,Murder,Homicide,NaN,May,10
...,...,...,...,...,...,...
143095,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,5.0,Nov,19
143096,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,7.0,Dec,19
143097,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,5.0,Jan,20
143098,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,1.0,Feb,20
143099,Wheatbelt District,Breach of Police Order,Breach of Violence Restraint Order,4.0,Mar,20

In [129]:
raw_crime_data.columns

Index(['District', 'Offence Group', 'Offence', 'Total Number of Offences',
       'Month', 'Year'],
      dtype='object')

In [130]:
#export to csv
raw_crime_data.to_csv('crimedataclean.csv',sep=',')

In [143]:
#group by district, year, offence
grouped = raw_crime_data.groupby(['District', 'Year', 'Offence Group']).sum()

grouped.head(50)

                                                                        Total Number of Offences
District          Year Offence Group
Armadale District 10   Assault Police Officer                                               45.0
                       Attempted / Conspiracy to Murder                                      1.0
                       Breach of Family Violence Restraint Order                           340.0
                       Breach of Police Order                                               74.0
                       Breach of Violence Restraint Order                                  109.0
                       Burglary (Dwelling)                                                2429.0
                       Burglary (Non-Dwelling)                                             531.0
                       Cause Bushfire                                                        4.0
                       Cause Damage by Fire                                                 93.0
                       Common Assault (Family)                                             515.0
                       Common Assault (Non-Family)                                         528.0
                       Criminal Damage                                                     305.0
                       Cultivate or Manufacture Drugs                                       97.0
                       Damage                                                             2574.0
                       Deprivation of Liberty                                               39.0
                       Driving Causing Death                                                 5.0
                       Drug Dealing                                                         75.0
                       Drug Possession                                                     573.0
                       Forgery                                                               7.0
                       Fraud (Credit Card)                                                   0.0
                       Fraud (Not Elsewhere Classified)                                    452.0
                       Graffiti                                                            836.0
                       Kidnapping / Child Stealing                                           2.0
                       Manslaughter                                                          1.0
                       Murder                                                                4.0
                       Non-Assaultive Sexual Offences                                       85.0
                       Other Drug Offences                                                   4.0
                       Other Fire Related Offences                                           0.0
                       Possess Stolen Property                                              99.0
                       Possess Weapon to Cause Fear (Family)                                18.0
                       Possess Weapon to Cause Fear (Non-Family)                            69.0
                       Possession of Drug Paraphernalia                                    285.0
                       Receiving Stolen Property                                            34.0
                       Regulated Weapons Offences                                          159.0
                       Robbery (Business)                                                    7.0
                       Robbery (Non-Business)                                              146.0
                       Serious Assault (Family)                                            175.0
                       Serious Assault (Non-Family)                                        300.0
                       Sexual Assault                                                      300.0
                       Stealing (Not Elsewhere Classified)                                4857.0
                       Stealing From Dwelling                                                0.0
                       Stealing From Motor Vehicle (Contents or Parts)                       0.0
                       Stealing From Other Premises or Place                                 0.0
                       Stealing From Retail Premises (Shoplift)                              0.0
                       Stealing as a Servant                                                16.0
                       Stealing of Motor Vehicle                                           622.0
                       Threatening Behaviour (Family)                                       57.0
                       Threatening Behaviour (Non-Family)                                  151.0
                  11   Assault Police Officer                                               35.0
                       Attempted / Conspiracy to Murder                                      0.0

NameError: name 'grouped_district' is not defined